# Generated by Django 3.2.8 on 2022-01-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('image6', models.ImageField(blank=True, upload_to='')),
                ('image7', models.ImageField(blank=True, upload_to='')),
                ('image8', models.ImageField(blank=True, upload_to='')),
                ('image9', models.ImageField(blank=True, upload_to='')),
                ('image10', models.ImageField(blank=True, upload_to='')),
                ('image11', models.ImageField(blank=True, upload_to='')),
                ('image12', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
